Resolve Issue #49
Milind220/Ozone pull request #103
Opened 2022-03-31 09:23 UTC by tariksouabny

*Made on branch `dev`*

Added list of parameters in docstrings of all data fetching functions

2022-03-31 09:40 UTC, Sam-damn requested changes
Looks great to me , however i noticed you missed two methods which also need the parameter list docstrings `get_specific_parameter` and `get_coordinate_air`

2022-04-01 07:38 UTC, Milind220 approved these changes
Awesome! adding that in now!

EDIT: I didn't see the request for changes above. This will be merged after this is addressed.

2022-04-02 10:14 UTC, Milind220 commented
@tariksouabny Hey, please address the changes that were mentioned above

2022-04-02 21:14 UTC, tariksouabny commented
Got it! Added the rest of the lists in the docstrings of `get_specific_parameter` and `get_coordinate_air`.

2022-04-02 22:29 UTC, Sam-damn requested changes

2022-04-02 22:29 UTC, Sam-damn commented on src/ozone/ozone.py
> +                    [ "aqi", "pm25", "pm10", "o3", "co", "no2", "so2", "dew", "h", "p",
@tariksouabny  thanks for addressing the requests,
the new changes you made however seem to be missing few parameters which need to be added  
```suggestion
								Choose from the following values:
                    [ "aqi", "pm25", "pm10", "o3", "co", "no2", "so2", "dew", "h", "p", "t", "w", "wg" ]
```

2022-04-02 22:29 UTC, Sam-damn commented on src/ozone/ozone.py
> +                    [ "aqi", "pm25", "pm10", "o3", "co", "no2", "so2", "dew", "h", "p",]
here as well
```suggestion
								Choose from the following values:
                    [ "aqi", "pm25", "pm10", "o3", "co", "no2", "so2", "dew", "h", "p", "t", "w", "wg"  ]
```

2022-04-02 22:31 UTC, Sam-damn approved these changes

2022-04-02 22:33 UTC, merged

2022-04-03 07:23 UTC, lahdjirayhan commented
🚀