Dev
Milind220/Ozone pull request #42
Opened 2022-03-03 19:58 UTC by antocommi

First ever pull request and commit!

2022-03-04 00:15 UTC, Sam-damn commented
@antocommi  just for future reference u should be performing your pull request on the dev branch and not main , the main branch should only be updated when new releases are ready to be published , that is in your forked repository u commit changes to the dev branch in your fork and then you start the pull request against the Milind220:main , if you want more details you can check the discussion tab it has information on the branching model that is used in this repository

2022-03-04 01:35 UTC, Milind220 commented
Hey @antocommi , I've changed the target branch of your PR from `main` to `dev`. This is because, as @Sam-damn pointed out, any commits to the `main` branch is automatically considered a new release. Instead we use the `dev` branch to make new changes, which makes sure that `main` is always stable.

Thanks for your contribution! I'll just review it :)

2022-03-04 02:34 UTC, Milind220 requested changes
I've left 3 change requests, all regarding the name of the methods. Well done though! everything works as expected :)

2022-03-04 02:34 UTC, Milind220 commented on src/ozone/ozone.py
> +            df = pandas.DataFrame(self.get_lat_lon_air(loc[0], loc[1], df=df, params=params))
I think you forgot to rename the `get_lat_long_air` method here. Rename to `get_coordinate_air`

2022-03-04 21:36 UTC, antocommi commented
Renamed the methods and changed the method reference

2022-03-05 02:18 UTC, Milind220 commented
@antocommi Awesome! thanks again for the contribution 💯

2022-03-05 02:18 UTC, Milind220 approved these changes

2022-03-05 02:19 UTC, merged