docs[README]: Add Ozone parameters section
Milind220/Ozone pull request #84
Opened 2022-03-23 22:55 UTC by kristinamancini

Added a section for Ozone's parameters under the code examples

2022-03-24 03:00 UTC, lahdjirayhan commented on README.md
> + * aqi: air quality index, a measurement of air quality that tells you how clean or polluted the air is
I would recommend changing aqi into `aqi` to make it more unambiguous that it's a code argument. Same for other parameters as well.

2022-03-24 11:50 UTC, Sam-damn requested changes
@kristinamancini i agree with @lahdjirayhan suggestion, it would be great if you could wrap the parameter's names in code segments so that they could stand out more than their description, and Great work!

2022-03-24 16:25 UTC, kristinamancini commented on README.md
> +### Ozone Parameters
All good! I agree, that wording sounds better.

2022-03-24 17:33 UTC, merged

2022-03-24 17:33 UTC, Sam-damn commented
Thank you @kristinamancini

2022-03-25 04:18 UTC, lahdjirayhan commented
All clear and thank you for your contribution! @kristinamancini